[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ChenSignatures = "4efb4129-5e83-47d2-926d-947c0e6cb76d"
DiffEqFinancial = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
